name: cash_field
description: A simple package to hold cash input value.
version: 0.0.1
repository: https://github.com/yanncabral/cash_field

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  intl: ^0.17.0
